apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
      - name: httpd
        image: httpd 
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/
            name: httpdvolume
        ports:
          - containerPort: 80
      volumes:
      - name: httpdvolume
        hostPath: 
          path: /c/Users/miyake/Desktop/
  selector:
    matchLabels:
      run: httpd